MonPortfolio/Models/ErrorViewModel.cs
using System;

namespace MonPortfolio.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MonPortfolio/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MonPortfolio.Models;

namespace MonPortfolio.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Confidentialite()
        {
            return View();
        }
        public IActionResult Moi()
        {
            return View();
        }
        public IActionResult MonEtablissement()
        {
            return View();
        }
        public IActionResult MaFormation()
        {
            return View();
        }
        public IActionResult MesCompetences()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MonPortfolio/Controllers/ProjetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MonPortfolio.Controllers
{
    public class ProjetController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MonPortfolio/Controllers/VeilleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MonPortfolio.Controllers
{
    public class VeilleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Juridique()
        {
            return View();
        }
        public IActionResult Technologique()
        {
            return View();
        }
    }
}

MonPortfolio/Views/Page/Confidentialite.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

MonPortfolio/Views/Page/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section class="section">
    <div class="hero fullscreen hero-img parallax-img" id="splash-img">
        <div class="hero-body">
            <div class="content u-text-center">
                <h1 class="uppercase white title headline-1">👋 Hello !</h1>
                <a class="u-inline-block" asp-area="" asp-controller="Page" asp-action="Moi">
                    <button class="btn-light outline">Commencer la visite</button>
                </a>
            </div>
        </div>
    </div>
</section>

MonPortfolio/Views/Page/MaFormation.cshtml
<div class="hero-body u-center">
    <div id="bts">
        <br>
        <h2>BTS SIO ?</h2>
        <div class="card-custom text-center">
            <p>
                Le BTS Services informatique aux Organisations est un diplôme reconnu par l’état de niveau Bac+2. Il remplace depuis septembre 2011 l’ancien BTS informatique de Gestion (BTS IG). En effet, cette nouvelle formule répond aux attentes de la profession en matière de qualification. Le programme a évolué en fonction de la place et du rôle des TIC (Technologies d’Information Communication) et propose deux spécialités bien distinctes : le BTS SIO SISR et le BTS SIO SLAM.
                Il associe aux enseignements théoriques et professionnels (en contrôle continu et final) deux stages en entreprise (10 à 11 semaines réparties sur les deux années d’études).
                En plus des matières en lien avec l’ingénierie informatique, la formation propose également des enseignements de culture générale, d’anglais (avec la possibilité de continuer une LV2), de mathématiques appliquées à l’informatique, ainsi que sur les outils d’analyse économique, managériale et juridique des services informatiques.
                De plus, au cours de cette formation, il est possible de bénéficier d’un enseignement approfondi en mathématiques et de travailler en autonomie en laboratoire informatique.
            </p>
        </div>
        <h2>BTS SIO EN DEUX OPTIONS </h2>
        <div class="card-custom text-center">
            <p>
                OPTION SISR
                <br />
                L’option Solutions d’infrastructure, systèmes et réseaux forme des professionnels des réseaux et équipements informatiques (installation, maintenance, sécurité). En sortant d’un BTS SIO SISR, vous serez capables de gérer et d’administrer le réseau d’une société et d’assurer sa sécurité et sa maintenance.
                Les techniciens supérieurs en informatique option SISR, peuvent accéder aux métiers de :
                •	Administrateur systèmes et réseaux,
                •	Informaticien support et déploiement,
                •	Pilote d’exploitation,
                •	Support systèmes et réseaux,
                •	Technicien d’infrastructure,
                •	Technicien de production,
                •	Technicien micro et réseaux
                <br />
                OPTION SLAM
                <br />
                L’option Solutions logicielles et applications métiers forme des spécialistes des logiciels (rédaction d’un cahier des charges, formulation des besoins et spécifications, développement, intégration au sein de la société).
                Les techniciens supérieurs en informatique option slam, sont préparés aux métiers de
                •	Développeur d’applications informatiques
                •	Développeur informatique
                •	Analyste d’applications ou d’études
                •	Analyste programmeur
                •	Chargé d’études informatiques
                •	Informaticien d’études
                •	Programmeur analyste
                •	Programmeur d’applications
                •	Responsable des services applicatifs
                •	Technicien d’études informatiques

            </p>
        </div>
    </div>

MonPortfolio/Views/Page/MesCompetences.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MonPortfolio/Views/Page/Moi.cshtml
<div class="hero-body u-center">
    <div id="moi">
        <br>
        <h2>A propos de moi</h2>
        <div class="card-custom text-center">
            <p>Je m’appelle Samuel Votier je suis née le 25/11/2002. 
            Je suis actuellement étudiant au Lycée Saint Aspais où je suis une formation en BTS SIO option SLAM « Services Informatiques aux Organisations option Solutions Logicielles et Applications Métier » pour la période 2020/2022. 
            Depuis mon plus jeune âge je baigne dans l’informatique et la technologie c’est ce qui m’a donné envie de poursuivre mes études postbac avec ce BTS SIO.</p>
        </div>
         <h2>Projet Professionnel</h2>
        <div class="card-custom text-center">
            <p>A l’heure actuelle j’ai comme projet professionnel de devenir développeur web ou d’application et de travailler pour une entreprise qui me correspond et par la suite après avoir acquis de l’expérience lancer une start-up toujours dans le domaine du développement. 
            Dans ce but je cherche à réaliser une formation diplômante bac+3.</p>
        </div>

    </div>
</div>


MonPortfolio/Views/Page/MonEtablissement.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MonPortfolio/Views/Projet/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MonPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonPortfolio</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <!-- Minified Cirrus CSS -->
    <link rel="stylesheet" href="~/lib/cirrus/cirrus.min.css">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="header header-fixed unselectable header-animated">
            <div class="header-brand">
                <div class="nav-item no-hover">
                    <h6 class="title"><a asp-area="" asp-controller="Page" asp-action="Index">MonPortfolio</a></h6>
                </div>
                <div class="nav-item nav-btn" id="header-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="header-nav" id="header-menu">
                <div class="nav-left">
                    <div class="nav-item text-center">
                        <a href="#">
                            <span class="icon">
                                <i class="fab fa-wrapper fa-twitter" aria-hidden="true"></i>
                            </span>
                        </a>
                    </div>
                </div>

                <div class="nav-right">
                    <div class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Page" asp-action="Index">Home</a>
                    </div>
                    <div class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Page" asp-action="Moi">Moi</a>
                    </div>
                    <div class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Page" asp-action="MonEtablissement">Mon établissement</a>
                    </div>
                    <div class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Page" asp-action="MaFormation">Ma formation</a>
                    </div>
                    <div class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Page" asp-action="MesCompetences">Mes compétences</a>
                    </div>
                    <div class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Projet" asp-action="Index">Mes projets</a>
                    </div>
                    <div class="nav-item has-sub toggle-hover">
                        <a class="nav-dropdown-link" >Ma veille</a>
                        <ul class="dropdown-menu dropdown-animated" role="menu">
                            <li role="menu-item"><a asp-area="" asp-controller="Veille" asp-action="Index">Présentation</a></li>
                            <li role="menu-item"><a asp-area="" asp-controller="Veille" asp-action="Technologique">Veille technologique</a></li>
                            <li role="menu-item"><a asp-area="" asp-controller="Veille" asp-action="Juridique">Veille juridique</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </header>

    <main role="main">
        @RenderBody()
    </main>


    <footer>
        <h6 class="white uppercase">Samuel Votier</h6>
        <div class="content">
            <div class="divider"></div>
            <div class="row">
                <div class="col-3">
                    <ul class="no-bullets">
                        <li class="no-bullets footer-list-title"><a asp-area="" asp-controller="Page" asp-action="Confidentialite">Confidentilalité</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

MonPortfolio/Views/Veille/Index.cshtml
<div class="hero-body u-center">
    <div class="hero fullscreen hero-img parallax-img" id="splash-img2">
        <div id="veille">
            <br>
            <div class="card-custom">
                <h2>Qu’est-ce qu’une veille ?</h2>

                <p>

                    La veille technologique est une activité qui met en œuvre des techniques d’acquisition, de stockage et d’analyse d’informations, concernant un produit ou un procédé, sur l’état de l’art et l’évolution de son environnement scientifique
                    , technique, industriel ou commercial, afin de collecter, organiser,
                    puis analyser et diffuser les informations pertinentes qui vont permettre d’anticiper les évolutions, et qui vont faciliter l’innovation.
                </p>
            </div>
        </div>
    </div>
</div>

MonPortfolio/Views/Veille/Juridique.cshtml
<div class="hero-body u-center">
    <div id="veille">
        <br>
        <h2>Qu’est-ce qu’une veille juridique ?</h2>
        <div class="card-custom">
            <p>
                La veille technologique est une activité qui met en œuvre des techniques d’acquisition, de stockage et d’analyse d’informations, concernant un produit ou un procédé, sur l’état de l’art et l’évolution de son environnement scientifique
                , technique, industriel ou commercial, afin de collecter, organiser,
                puis analyser et diffuser les informations pertinentes qui vont permettre d’anticiper les évolutions, et qui vont faciliter l’innovation.
            </p>
        </div>
    </div>
</div>

MonPortfolio/Views/Veille/Technologique.cshtml
<div class="hero-body u-center">
    <div id="veille">
        <br>
        <h2>Qu’est-ce qu’une veille technologique ?</h2>
        <div class="card-custom">
            <p>
                La veille technologique est une activité qui met en œuvre des techniques d’acquisition, de stockage et d’analyse d’informations, concernant un produit ou un procédé, sur l’état de l’art et l’évolution de son environnement scientifique
                , technique, industriel ou commercial, afin de collecter, organiser,
                puis analyser et diffuser les informations pertinentes qui vont permettre d’anticiper les évolutions, et qui vont faciliter l’innovation.
            </p>
        </div>
    </div>
</div>